package dbTABLES;

// Generated May 29, 2013 2:33:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * Postdb generated by hbm2java
 */
public class Postdb implements java.io.Serializable {

	private int idpost;
	private Threaddb threaddb;
	private Memberdb memberdb;
	private String title;
	private String content;

	public Postdb() {
	}

	public Postdb(int idpost) {
		this.idpost = idpost;
	}

	public Postdb(int idpost, Threaddb threaddb, Memberdb memberdb,
			String title, String content) {
		this.idpost = idpost;
		this.threaddb = threaddb;
		this.memberdb = memberdb;
		this.title = title;
		this.content = content;
	}

	public int getIdpost() {
		return this.idpost;
	}

	public void setIdpost(int idpost) {
		this.idpost = idpost;
	}

	public Threaddb getThreaddb() {
		return this.threaddb;
	}

	public void setThreaddb(Threaddb threaddb) {
		this.threaddb = threaddb;
	}

	public Memberdb getMemberdb() {
		return this.memberdb;
	}

	public void setMemberdb(Memberdb memberdb) {
		this.memberdb = memberdb;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
