package dbTABLES;

// Generated May 29, 2013 2:33:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import Sadna.db.SubForum;

/**
 * Subforumdb generated by hbm2java
 */
public class Subforumdb implements java.io.Serializable {

	private Integer idsubforum;
	private Forumdb forumdb;
	private String subForumName;
	private Set<Memberdb> memberdbs = new HashSet<Memberdb>(0);
	private Set<Threaddb> threaddbs = new HashSet<Threaddb>(0);

	public Subforumdb() {
	}

	public Subforumdb(Forumdb forumdb, String subForumName,
			Set<Memberdb> memberdbs, Set<Threaddb> threaddbs) {
		this.forumdb = forumdb;
		this.subForumName = subForumName;
		this.memberdbs = memberdbs;
		this.threaddbs = threaddbs;
	}

	public SubForum convertToSubForum(){
		return new SubForum(forumdb.convertToForum(), subForumName);
	}
	
	public Integer getIdsubforum() {
		return this.idsubforum;
	}

	public void setIdsubforum(Integer idsubforum) {
		this.idsubforum = idsubforum;
	}

	public Forumdb getForumdb() {
		return this.forumdb;
	}

	public void setForumdb(Forumdb forumdb) {
		this.forumdb = forumdb;
	}

	public String getSubForumName() {
		return this.subForumName;
	}

	public void setSubForumName(String subForumName) {
		this.subForumName = subForumName;
	}

	public Set<Memberdb> getMemberdbs() {
		return this.memberdbs;
	}

	public void setMemberdbs(Set<Memberdb> memberdbs) {
		this.memberdbs = memberdbs;
	}

	public Set<Threaddb> getThreaddbs() {
		return this.threaddbs;
	}

	public void setThreaddbs(Set<Threaddb> threaddbs) {
		this.threaddbs = threaddbs;
	}

}
