package dbTABLES;

// Generated May 29, 2013 2:33:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import Sadna.db.ThreadMessage;

/**
 * Threaddb generated by hbm2java
 */
public class Threaddb implements java.io.Serializable {

	private int idthread;
	private Subforumdb subforumdb;
	private Memberdb memberdb;
	private String title;
	private String content;
	private Set<Postdb> postdbs = new HashSet<Postdb>(0);

	public Threaddb() {
	}

	public Threaddb(int idthread) {
		this.idthread = idthread;
	}

	public Threaddb(int idthread, Subforumdb subforumdb, Memberdb memberdb,
			String title, String content, Set<Postdb> postdbs) {
		this.idthread = idthread;
		this.subforumdb = subforumdb;
		this.memberdb = memberdb;
		this.title = title;
		this.content = content;
		this.postdbs = postdbs;
	}

	public ThreadMessage convertToThread(){
		return new ThreadMessage(subforumdb.convertToSubForum(), title, content, memberdb.getUserName());
	}
	
	
	public int getIdthread() {
		return this.idthread;
	}

	public void setIdthread(int idthread) {
		this.idthread = idthread;
	}

	public Subforumdb getSubforumdb() {
		return this.subforumdb;
	}

	public void setSubforumdb(Subforumdb subforumdb) {
		this.subforumdb = subforumdb;
	}

	public Memberdb getMemberdb() {
		return this.memberdb;
	}

	public void setMemberdb(Memberdb memberdb) {
		this.memberdb = memberdb;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set<Postdb> getPostdbs() {
		return this.postdbs;
	}

	public void setPostdbs(Set<Postdb> postdbs) {
		this.postdbs = postdbs;
	}

}
